blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogsView.as_view()), name='blogs'),
    path('blogs/user/', UserBlogsView.as_view(), name='user_blogs'),
    path('blogs/create/', cache_page(600)(BlogCreateView.as_view()), name='create_blog'),
    path('blogs/user_blog/<slug:slug>', UserBlogView.as_view(), name='user_view_blog'),
    path('blogs/blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blogs/blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('messaging.urls', namespace='messaging')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messaging.apps import MessagingConfig
from messaging.views import *

app_name = MessagingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('clients/', cache_page(60)(AllClientsView.as_view()), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/client/<int:pk>',  cache_page(600)(ClientView.as_view()), name='view_client'),
    path('clients/client/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('clients/client/update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),

    path('messages/', cache_page(60)(AllMessagesView.as_view()), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/message/<int:pk>', cache_page(600)(MessageView.as_view()), name='view_message'),
    path('messages/message/delete/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('messages/message/update/<int:pk>', MessageUpdateView.as_view(), name='update_message'),

    path('mailing/', cache_page(60)(AllUserMailingView.as_view()), name='user_mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/view/<int:pk>', cache_page(600)(UserMailingView.as_view()), name='user_view_mailing'),
    path('mailing/delete/<int:pk>', UserMailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/update/<int:pk>', UserMailingUpdateView.as_view(), name='update_mailing'),

    path('moderator/mailing/', ModeratorAllMailingView.as_view(), name='moderator_mailing'),
    path('moderator/users/', ModeratorAllUsersView.as_view(), name='moderator_users'),

    path('log/', AllUserLogView.as_view(), name='moderator_log'),
]

blog/models.py
from django.db import models
from services.utils import unique_slugify

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """ Модель статьи (блога) """
    name = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=255, verbose_name='url')
    content = models.TextField(max_length=1000, verbose_name='содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(verbose_name='дата создания')
    publication = models.BooleanField(default=False, verbose_name='признак публикации')
    user_owner = models.ForeignKey('users.user', on_delete=models.PROTECT, verbose_name='Владелец клиента')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.name}'

    def delete(self, using=None, keep_parents=False):
        """ Удаление статьи """
        self.publication = False
        self.save()

    def save(self, *args, **kwargs):
        """ Сохранение полей модели при их отсутствии заполнения """
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from services.forms import FormStyleMixin


class BlogCreateViewForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания клиента """
    class Meta:
        model = Blog
        fields = ('name', 'content', 'image', 'date_of_creation')

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from blog.forms import BlogCreateViewForm
from blog.models import Blog


class BlogsView(ListView):
    """ Все блоги с активной публикацией """
    model = Blog
    template_name = 'blog/blogs.html'
    extra_context = {
        'title': 'Статьи'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication=True)
        return queryset


class UserBlogsView(ListView):
    """ Все блоги данного пользователя """
    model = Blog
    extra_context = {
        'title': 'Статьи'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_owner=self.request.user)
        return queryset


class BlogCreateView(CreateView):
    """ Создание блога """
    model = Blog
    form_class = BlogCreateViewForm

    def get_success_url(self):
        """ Берем slug из данного объекта """
        print()
        return reverse_lazy('blog:view_blog', args=(self.object.slug,))

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.user_owner = self.request.user
        # Сохраняет в бд
        self.object.save()
        return super(BlogCreateView, self).form_valid(form)


class BlogUpdateView(UpdateView):
    """ Обновление блога """
    model = Blog
    form_class = BlogCreateViewForm
    success_url = reverse_lazy('blog:blogs')


class BlogDeleteView(DeleteView):
    """ Удаление блога """
    model = Blog
    success_url = reverse_lazy('blog:blogs')


class BlogView(DetailView):
    """ Отображение блога без каких либо прав """
    model = Blog
    extra_context = {
        'title': 'Статья'
    }

    def get_object(self, queryset=None):
        """ Получает объект, увеличивает просмотры """
        object_blog = super().get_object()
        object_blog.number_of_views += 1
        object_blog.save()
        return object_blog


class UserBlogView(DetailView):
    """ Отображение одного блога принадлежащего данному пользователю """
    model = Blog
    template_name = 'blog/user_blog.html'
    extra_context = {
        'title': 'Статья'
    }

blog/templates/blog/blog_confirm_delete.html
{% extends 'messaging/base.html' %}

{% block content %}

{% if object.user_owner == user %}

<br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <h5 style="color: orange;">Удаление статьи</h5>
            </div>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                Уверены, что хотите удалить статью "{{ object }}"?<br><br>
                <input type="submit" class="btn btn-outline-danger" value="Подтвердите удаление">
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'blog:blogs' %}" class="btn btn-outline-secondary">Назад</a>
        </div>
    </div>
</div>
</center>

{% else %}

{% include 'messaging/access_is_closed.html' %}

{% endif %}

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'messaging/base.html' %}
{% load FilterExtension %}

{% block content %}

<br>
<center>
<div class="col-10">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h5 style="color: #0f5132;">{{ object.name }}</h5></td>
                    </tr>
                    <tr>
                        <td><a href="{% url 'blog:view_blog' object.slug %}">{{ object.slug }}</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <tr>
                    <td>
                        <p>{{ object.content }}</p>
                        <p style="color: #aaaaaa;">Дата создания: {{ object.date_of_creation }}</p>
                        <small style="color: orange;">Количество просмотров: {{ object.number_of_views }}</small>
                        <p style="color: #999999;">
                        {% if object.user_owner.first_name %}
                        Имя автора: {{ object.user_owner.first_name }}
                        {% else %}
                        Имя автора: неизвестно
                        {% endif %}
                        </p>
                    </td>
                    <td>
                        <img src="{{ object.image|mediapath }}" style="width: 400px; margin: 15px;" class="card-img" alt="">
                    </td>
                </tr>
            </table>

        </div>
        <div class="card-footer">
            <table class="table">
                <tr class="text-center">
                    <td>
                        <a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:blogs' %}" class="btn btn-outline-secondary">К списку статей</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
</center>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'messaging/base.html' %}

{% block content %}

<br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>{% if object %}Измените данные статьи.{% else %}Добавьте новую статью.{% endif %}</p>
            </div>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {% if object %}
                    {% if object.user_owner == user %}
                        <button type="submit" class="btn btn-outline-secondary">Сохранить</button>
                    {% endif %}
                {% else %}
                    <button type="submit" class="btn btn-outline-secondary">Добавить</button>
                {% endif %}
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'blog:blogs' %}" class="btn btn-outline-secondary">Список статей</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'messaging/base.html' %}

{% block content %}

<br>
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h5 style="color: orange;">{{ title }}</h5></td>
                        <td style="text-align: right;"><a href="{% url 'blog:create_blog' %}" class="btn btn-outline-secondary">Добавить новую статью</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <tr>
                    <td><p>Slug</p></td>
                    <td><p>Название</p></td>
                    <td><p>Дата создания</p></td>
                    <td><p>Количество просмотров</p></td>
                    <td></td>
                    <td></td>
                </tr>

            {% for object in object_list %}


                <tr>
                    <td>
                        <a href="{% url 'blog:user_view_blog' object.slug %}">{{ object.slug }}</a>
                    </td>
                    <td>
                        {{ object.name }}
                    </td>
                    <td>
                        {{ object.date_of_creation }}
                    </td>
                    <td>
                        {{ object.number_of_views }}
                    </td>
                    <td>
                        <a href="{% url 'blog:update_blog' object.slug %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:delete_blog' object.slug %}" class="btn btn-outline-danger">Удалить</a>
                    </td>
                </tr>


            {% endfor %}

            </table>

        </div>
        <div class="card-footer">
            <center><a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a></center>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogs.html
{% extends 'messaging/base.html' %}
{% load FilterExtension %}
{% block content %}

{% for object in object_list %}

<br>
<center>
<div class="col-10">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h5 style="color: #0f5132;">{{ object.name }}</h5></td>
                    </tr>
                    <tr>
                        <td><a href="{% url 'blog:view_blog' object.slug %}">{{ object.slug }}</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <tr>
                    <td>
                        <p>{{ object.content }}</p>
                        <p style="color: #aaaaaa;">Дата создания: {{ object.date_of_creation }}</p>
                        <small style="color: orange;">Количество просмотров: {{ object.number_of_views }}</small>
                    </td>
                    <td>
                        <img src="{{ object.image|mediapath }}" style="width: 400px; margin: 15px;" class="card-img" alt="">
                    </td>
                </tr>
            </table>

        </div>
        <div class="card-footer">
            <p style="color: #999999;">
            {% if object.user_owner.first_name %}
            Имя автора: {{ object.user_owner.first_name }}
            {% else %}
            Имя автора: неизвестно
            {% endif %}
            </p>
        </div>
    </div>
</div>
</center>

{% endfor %}

{% endblock %}

blog/templates/blog/user_blog.html
{% extends 'messaging/base.html' %}
{% load FilterExtension %}

{% block content %}

<br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <h5 style="color: orange;">{{ title }}</h5>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>
                        Название:
                    </td>
                    <td>
                        {{ object.name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Содержимое:
                    </td>
                    <td>
                        {{ object.content }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Изображение:
                    </td>
                    <td>
                        <img src="{{ object.image|mediapath }}" class="img-fluid" alt="">
                    </td>
                </tr>
                <tr>
                    <td>
                        Дата создания:
                    </td>
                    <td>
                        {{ object.date_of_creation }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Количество просмотров:
                    </td>
                    <td>
                        {{ object.number_of_views }}
                    </td>
                </tr>
                <tr class="text-center">
                    {% if object.user_owner == user %}
                    <td>
                        <a href="{% url 'blog:update_blog' object.slug %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:delete_blog' object.slug %}" class="btn btn-outline-danger">Удалить</a>
                    </td>
                    {% endif %}
                </tr>
            </table>
        </div>
        <div class="card-footer">
            <table class="table">
                <tr class="text-center">
                    <td>
                        <a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:user_blogs' %}" class="btn btn-outline-secondary">К списку статей</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
</center>

{% endblock %}