blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogsView.as_view()), name='blogs'),
    path('blogs/user/', UserBlogsView.as_view(), name='user_blogs'),
    path('blogs/create/', cache_page(600)(BlogCreateView.as_view()), name='create_blog'),
    path('blogs/user_blog/<slug:slug>', UserBlogView.as_view(), name='user_view_blog'),
    path('blogs/blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blogs/blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('messaging.urls', namespace='messaging')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messaging.apps import MessagingConfig
from messaging.views import *

app_name = MessagingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('clients/', cache_page(60)(AllClientsView.as_view()), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/client/<int:pk>',  cache_page(600)(ClientView.as_view()), name='view_client'),
    path('clients/client/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('clients/client/update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),

    path('messages/', cache_page(60)(AllMessagesView.as_view()), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/message/<int:pk>', cache_page(600)(MessageView.as_view()), name='view_message'),
    path('messages/message/delete/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('messages/message/update/<int:pk>', MessageUpdateView.as_view(), name='update_message'),

    path('mailing/', cache_page(60)(AllUserMailingView.as_view()), name='user_mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/view/<int:pk>', cache_page(600)(UserMailingView.as_view()), name='user_view_mailing'),
    path('mailing/delete/<int:pk>', UserMailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/update/<int:pk>', UserMailingUpdateView.as_view(), name='update_mailing'),

    path('moderator/mailing/', ModeratorAllMailingView.as_view(), name='moderator_mailing'),
    path('moderator/users/', ModeratorAllUsersView.as_view(), name='moderator_users'),

    path('log/', AllUserLogView.as_view(), name='moderator_log'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', UserActivate.as_view(), name='verify_email'),
    path('user_activate', TemplateView.as_view(template_name='users/user_activate.html'), name='user_activate'),
    path('invalid_user_activate/', InvalidUserActivate.as_view(), name='invalid_user_activate'),
    path('reset_password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update', ProfileUpdateView.as_view(), name='profile_update'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager as UserBaseManager
from django.db import models
from django.apps import apps


NULLABLE = {'blank': True, 'null': True}


class UserManager(UserBaseManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    email_verify = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms

from services.forms import FormStyleMixin
from users.models import User


class UserForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetDoneView, PasswordContextMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import UpdateView, CreateView, FormView, TemplateView
from pip._internal.utils._jaraco_text import _
from services.utils import generation_password
from config import settings
from users.forms import UserRegisterForm, UserForm
from users.models import User


class RegisterView(CreateView):
    """ Регистрация пользователя """
    model = User
    form_class = UserRegisterForm

    def form_valid(self, form):
        """ Дружественное письмо на почту пользователя, после регистрации """
        new_user = form.save()
        uid = urlsafe_base64_encode(force_bytes(new_user.pk))
        new_token = token_generator.make_token(new_user)
        activation_url = reverse_lazy('users:verify_email', kwargs={'uidb64': uid, 'token': new_token})
        send_mail(
            subject='Сервис рассылки - Активация учетной записи',
            message=f'Убедительная просьба: если хотите закончить регистрацию, пройдите по ссылке: http://127.0.0.1:8000/{ activation_url }',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
            fail_silently=False
        )
        return redirect('users:confirm_email')


class UserActivate(View):
    """ Активация пользователя из письма """
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        # Сравнение токенов
        if user is not None and token_generator.check_token(user, token):
            # В случае удачи, активирует нового пользователя флагом True, сохраняет обЪект, логинится и отправляет письмо на почту
            user.email_verify = True
            user.save()
            login(request, user)
            send_mail(
                subject='Сервис рассылки - Успешная активация',
                message=f'Вы успешно активировали учетную запись!\nС уважением администрация сервиса рассылки.',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
            return redirect('users:user_activate')
        return redirect('users:invalid_user_activate')


    @staticmethod
    def get_user(uidb64):
        """ Получение пользователя """
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user


class InvalidUserActivate(TemplateView):
    """ Случай неудачной активации """
    template_name = 'users/invalid_user_activate.html'


class UserPasswordResetView(PasswordContextMixin, FormView):
    """ Сброс пароля, генерация нового с отправкой на email """
    form_class = PasswordResetForm
    success_url = reverse_lazy("users:password_reset_done")
    title = _("Password reset")
    template_name = 'users/password_reset_form.html'

    def form_valid(self, form):
        """ Получает email, по email получает пользователя, генерирует и присваивает новый пароль,
        отправляет пароль на почту  """
        user_email: str = self.request.POST.get('email')
        new_password: str = generation_password()
        user_object: object = User.objects.get(email=user_email)
        send_mail(
            subject='Сервис рассылки - Восстановление пароля',
            message=f'Вас приветствует администрация сервиса рассылки.\nВы запросили новый пароль для {user_email}.\nВаш новый пароль: {new_password}\nС уважением администрация сервиса рассылки.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user_email]
        )
        user_object.set_password(new_password)
        user_object.save()
        return super().form_valid(form)


class UserPasswordResetDoneView(PasswordResetDoneView):
    PasswordResetDoneView.template_name = 'users/password_reset_done.html'


class ProfileView(TemplateView):
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирование профиля """
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/confirm_email.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Регистрация пользователя прошла успешно.</p>
            </div>
        </div>
        <div class="card-body">
            <div class="about-info">
                <br>
                <p>Вам на почту отправлена ссылка, для подтверждения регистрации.</p>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'messaging:home' %}" class="btn btn-success">На главную</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/invalid_user_activate.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Ошибка верификации.</p>
            </div>
        </div>
        <div class="card-body">
             <div class="about-info">
                <br>
                <p>Ваша ссылка не работает, попробуйте снова.</p>
             </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:register' %}" class="btn btn-success">Регистрация</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/login.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Пожалуйста, пройдите аутентификацию.</p>
            </div>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:reset_password' %}" class="btn btn-danger">Забыли пароль?</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Смена пароля завершена.</p>
            </div>
        </div>
        <div class="card-body">
            <div class="about-info">
                <br>
                <p>Мы отправили вам новый пароль на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.
            Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:login' %}" class="btn btn-success">Перейти к авторизации пользователя</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Отправка временного пароля на email.</p>
            </div>
        </div>
        <div class="card-body">
             <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Отправить новый пароль на почту</button>
            </form>
        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/profile.html
{% extends 'messaging/base.html' %}
{% load FilterExtension %}

{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <h5 style="color: orange;">Профиль пользователя {{ user.email }}</h5>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td class="text-center" colspan="2">
                        {% if user.avatar %}
                            <img style="width: 300px; margin: 15px;" src="{{ user.avatar|mediapath }}" alt="Avatar">
                        {% else %}
                            <img style="width: 300px; margin: 15px;" src="http://127.0.0.1:8000/media/users/Not_ava.jpg" alt="Not Avatar">
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>
                        Имя:
                    </td>
                    <td>
                        {{ user.first_name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Фамилия:
                    </td>
                    <td>
                        {{ user.last_name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Телефон:
                    </td>
                    <td>
                        {{ user.phone }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Страна:
                    </td>
                    <td>
                        {{ user.country }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Почта:
                    </td>
                    <td>
                        {{ user.email }}
                    </td>
                </tr>
            </table>
        </div>
        <div class="card-footer">
            <table>
                <tr class="text-center">
                    <td>
                        <a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a>
                    </td>
                    <td>
                        <a href="{% url 'users:profile_update' %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/user_activate.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>Верификация прошла успешно!</p>
            </div>
        </div>
        <div class="card-body">
            <div class="about-info">
                <br>
                <p>Ваша учетная запись успешно активирована!</p>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'messaging:home' %}" class="btn btn-success">На главную</a>
        </div>
    </div>
</div>
</center>

{% endblock %}

users/templates/users/user_form.html
{% extends 'messaging/base.html' %}
{% block content %}

<br><br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <br>
                <p>
                    {% if user.is_authenticated %}
                        Обновление профиля.
                    {% else %}
                        Пожалуйста, зарегистрируйтесь.
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</center>

{% endblock %}