blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogsView.as_view()), name='blogs'),
    path('blogs/user/', UserBlogsView.as_view(), name='user_blogs'),
    path('blogs/create/', cache_page(600)(BlogCreateView.as_view()), name='create_blog'),
    path('blogs/user_blog/<slug:slug>', UserBlogView.as_view(), name='user_view_blog'),
    path('blogs/blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blogs/blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('messaging.urls', namespace='messaging')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messaging.apps import MessagingConfig
from messaging.views import *

app_name = MessagingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('clients/', cache_page(60)(AllClientsView.as_view()), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/client/<int:pk>',  cache_page(600)(ClientView.as_view()), name='view_client'),
    path('clients/client/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('clients/client/update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),

    path('messages/', cache_page(60)(AllMessagesView.as_view()), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/message/<int:pk>', cache_page(600)(MessageView.as_view()), name='view_message'),
    path('messages/message/delete/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('messages/message/update/<int:pk>', MessageUpdateView.as_view(), name='update_message'),

    path('mailing/', cache_page(60)(AllUserMailingView.as_view()), name='user_mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/view/<int:pk>', cache_page(600)(UserMailingView.as_view()), name='user_view_mailing'),
    path('mailing/delete/<int:pk>', UserMailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/update/<int:pk>', UserMailingUpdateView.as_view(), name='update_mailing'),

    path('moderator/mailing/', ModeratorAllMailingView.as_view(), name='moderator_mailing'),
    path('moderator/users/', ModeratorAllUsersView.as_view(), name='moderator_users'),

    path('log/', AllUserLogView.as_view(), name='moderator_log'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', UserActivate.as_view(), name='verify_email'),
    path('user_activate', TemplateView.as_view(template_name='users/user_activate.html'), name='user_activate'),
    path('invalid_user_activate/', InvalidUserActivate.as_view(), name='invalid_user_activate'),
    path('reset_password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update', ProfileUpdateView.as_view(), name='profile_update'),
]

messaging/forms.py
from django import forms

from messaging.models import Client, Message, Mailing
from services.forms import FormStyleMixin


class ClientCreateViewForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания клиента """
    class Meta:
        model = Client
        fields = ('email', 'surname', 'name', 'patronymic', 'comments')


class MessageCreateViewForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания сообщения """
    class Meta:
        model = Message
        fields = ('topic', 'text')


class MailingCreateViewForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания рассылки """
    class Meta:
        model = Mailing
        fields = ('name', 'dtime_begin', 'dtime_end', 'frequency', 'message')

messaging/views.py
import random

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, FormView

from blog.models import Blog
from messaging.forms import ClientCreateViewForm, MessageCreateViewForm, MailingCreateViewForm
from messaging.models import Client, Message, Mailing, Log
from services.cache import get_moderator_mailing_subjects, get_moderator_users_subjects
from services.celery_beat import AddTask
from users.models import User


class HomeView(ListView):
    """ Главная страница """
    model = Client
    template_name = 'messaging/main.html'
    extra_context = {
        'title': ''
    }

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передает три статьи из блога
        blog_list = Blog.objects.filter(publication=True)
        blog_random_list = random.sample(list(blog_list), 3)
        context_data['blog1'] = blog_random_list[0]
        context_data['blog2'] = blog_random_list[1]
        context_data['blog3'] = blog_random_list[2]

        # Получает количество рассылок
        mailing_count = Mailing.objects.count()
        context_data['mailing_count'] = mailing_count

        # Получает количество активных рассылок
        mailing_count_active = Mailing.objects.filter(status='launched').count()
        context_data['mailing_count_active'] = mailing_count_active

        # Получает количество уникальных клиентов
        users_count = User.objects.count()
        context_data['users_count'] = users_count

        return context_data


class ClientCreateView(LoginRequiredMixin, CreateView):
    """ Добавление нового клиента в БД """
    model = Client
    form_class = ClientCreateViewForm

    def get_success_url(self):
        """ Берем id из данного объекта """
        return reverse_lazy('messaging:view_client', args=(self.object.id,))

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.user_owner = self.request.user
        # Сохраняет в бд
        self.object.save()
        return super(ClientCreateView, self).form_valid(form)


class ClientView(LoginRequiredMixin, DetailView):
    """ Отображение одного клиента """
    model = Client

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class AllClientsView(LoginRequiredMixin, ListView):
    """ Список клиентов """
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_owner=self.request.user)
        return queryset


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление клиента """
    model = Client
    success_url = reverse_lazy('messaging:clients')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """ Обновление информации клиента """
    model = Client
    form_class = ClientCreateViewForm
    template_name = 'messaging/client_form.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('messaging:update_client', args=[self.get_object().pk])


class MessageCreateView(LoginRequiredMixin, CreateView):
    """ Добавление нового сообщения в БД """
    model = Message
    form_class = MessageCreateViewForm

    def get_success_url(self):
        """ Берем id из данного объекта """
        return reverse_lazy('messaging:view_message', args=(self.object.id,))

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.user_owner = self.request.user
        # Сохраняет в бд
        self.object.save()
        return super(MessageCreateView, self).form_valid(form)


class MessageView(LoginRequiredMixin, DetailView):
    """ Отображение одного сообщения """
    model = Message

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class AllMessagesView(LoginRequiredMixin, ListView):
    """ Список клиентов """
    model = Message
    extra_context = {
        'title': 'Список сообщений'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_owner=self.request.user)
        return queryset


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление клиента """
    model = Message
    success_url = reverse_lazy('messaging:messages')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """ Обновление информации сообщения """
    model = Message
    form_class = MessageCreateViewForm
    template_name = 'messaging/message_form.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('messaging:update_message', args=[self.get_object().pk])


class AllUserMailingView(LoginRequiredMixin, ListView):
    """ Список клиентов """
    model = Mailing
    template_name = 'messaging/user_mailing.html'
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_owner=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    """ Добавление новой рассылки в БД """
    model = Mailing
    form_class = MailingCreateViewForm

    def get_success_url(self):
        """ Берем id из данного объекта """
        return reverse_lazy('messaging:user_view_mailing', args=(self.object.id,))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Получает клиентов пользователя
        client_list = Client.objects.filter(user_owner=self.request.user)
        client_list = list(client_list)
        context_data['client_list'] = client_list

        return context_data

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.user_owner = self.request.user
        # Сохраняет в бд
        self.object.save()

        # Получает клиентов пользователя
        client_list = Client.objects.filter(user_owner=self.request.user)
        client_list = list(client_list)
        # Получает POST словарь
        post_dict = dict(self.request.POST.items())
        # Строит связь clients = все клиенты пользователя
        for client in client_list:
            # Если в ПОСТ есть клиент принадлежащий пользователю добавляет связь
            if client.email in post_dict:
                self.object.clients.add(client)

        # Добавляет задачу в БД
        # Переодичность рассылки
        every = self.object.frequency
        # Имя для задачи(передает id для дальнейшего поиска рассылки)
        name_id = self.object.id
        AddTask(every=every, name=name_id)

        return super(MailingCreateView, self).form_valid(form)


class UserMailingView(LoginRequiredMixin, DetailView):
    """ Отображение одной рассылки """
    model = Mailing
    template_name = 'messaging/user_mailing_view.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class UserMailingDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление рассылки """
    model = Mailing
    success_url = reverse_lazy('messaging:user_mailing')


class UserMailingUpdateView(LoginRequiredMixin, UpdateView):
    """ Обновление информации рассылки """
    model = Mailing
    form_class = MailingCreateViewForm
    template_name = 'messaging/mailing_form.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Получает клиентов пользователя
        client_list = Client.objects.filter(user_owner=self.request.user)
        client_list = list(client_list)
        context_data['client_list'] = client_list

        # Получает клиентов данной рассылки
        mailing_list = list(self.object.clients.all())
        context_data['mailing_list'] = mailing_list

        return context_data

    def get_success_url(self, *args, **kwargs):
        return reverse('messaging:update_mailing', args=[self.get_object().pk])

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """

        # Получает клиентов пользователя
        client_list = Client.objects.filter(user_owner=self.request.user)
        client_list = list(client_list)

        # Получает клиентов данной рассылки
        mailing_list = list(self.object.clients.all())

        # Получает POST словарь
        post_dict = dict(self.request.POST.items())
        # Строит связь clients = все клиенты пользователя
        for client in client_list:
            # Если в ПОСТ есть клиент принадлежащий пользователю добавляет связь
            if client.email in post_dict:
                self.object.clients.add(client)
            else:
                # Если обЬект в списке не выбранных клиентов, удаляет связь
                if client in mailing_list:
                    self.object.clients.remove(client)

        # Добавляет задачу в БД
        # Переодичность рассылки
        every = self.object.frequency

messaging/templates/messaging/access_is_closed.html
<br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
            </div>
        </div>
        <div class="card-body">
            <h1 style="color: red;">Доступ закрыт!</h1>
        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</center>

messaging/templates/messaging/client_detail.html
{% extends 'messaging/base.html' %}

{% block content %}

{% if object.user_owner == user %}

<br>
<center>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <h5 style="color: orange;">Клиент: {{ title }}</h5>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>
                        Email:
                    </td>
                    <td>
                        {{ object.email }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Фамилия:
                    </td>
                    <td>
                        {{ object.surname }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Имя:
                    </td>
                    <td>
                        {{ object.name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Отчество:
                    </td>
                    <td>
                        {{ object.patronymic }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Комментарий:
                    </td>
                    <td>
                        {{ object.comments }}
                    </td>
                </tr>
                <tr class="text-center">
                    <td>
                        <a href="{% url 'messaging:update_client' object.id %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                    <td>
                        <a href="{% url 'messaging:delete_client' object.id %}" class="btn btn-outline-danger">Удалить</a>
                    </td>
                </tr>
            </table>
        </div>
        <div class="card-footer">
            <table class="table">
                <tr class="text-center">
                    <td>
                        <a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a>
                    </td>
                    <td>
                        <a href="{% url 'messaging:clients' %}" class="btn btn-outline-secondary">К списку клиентов</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
</center>

{% else %}

{% include 'messaging/access_is_closed.html' %}

{% endif %}

{% endblock %}

messaging/templates/messaging/client_list.html
{% extends 'messaging/base.html' %}

{% block content %}

<br>
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h3 style="color: orange;">{{ title }}</h3></td>
                        <td style="text-align: right;"><a href="{% url 'messaging:create_client' %}" class="btn btn-outline-secondary">Добавить нового клиента</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <tr>
                    <td><p>Email</p></td>
                    <td><p>Фамилия</p></td>
                    <td><p>Имя</p></td>
                    <td><p>Отчество</p></td>
                    <td><p>Комментарий</p></td>
                    <td></td>
                    <td></td>
                </tr>

            {% for object in object_list %}


                <tr>
                    <td>
                        <a href="{% url 'messaging:view_client' object.id %}">{{ object.email }}</a>
                    </td>
                    <td>
                        {{ object.surname }}
                    </td>
                    <td>
                        {{ object.name }}
                    </td>
                    <td>
                        {{ object.patronymic }}
                    </td>
                    <td>
                        {{ object.comments }}
                    </td>
                    <td>
                        <a href="{% url 'messaging:update_client' object.id %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                    <td>
                        <a href="{% url 'messaging:delete_client' object.id %}" class="btn btn-outline-danger">Удалить</a>
                    </td>
                </tr>


            {% endfor %}

            </table>

        </div>
        <div class="card-footer">
            <center><a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a></center>
        </div>
    </div>
</div>

{% endblock %}

messaging/templates/messaging/moderator_mailing.html
{% extends 'messaging/base.html' %}

{% block content %}

<br>
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h3 style="color: orange;">{{ title }}</h3></td>
                        <td style="text-align: right;"><a href="{% url 'messaging:create_mailing' %}" class="btn btn-outline-secondary">Добавить, новую рассылку</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">
            <form method="get" action="{% url 'messaging:moderator_mailing' %}">
                {% csrf_token %}

            {% for object in object_list %}

                <br>
                <center>
                <div class="col-10">
                    <div class="card">
                        <div class="card-header">
                            <div class="about-info">
                                <h5 style="color: orange;">{{ object.name }}</h5>
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td width="60%">
                                        <p>Дата и время запуска рассылки:</p>
                                    </td>
                                    <td>
                                        {{ object.dtime_begin }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Дата и время остановки рассылки:</p>
                                    </td>
                                    <td>
                                        {{ object.dtime_end }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Периодичность рассылки:</p>                                    </td>
                                    <td>
                                        {{ object.frequency }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Статус:</p>
                                    </td>
                                    <td>
                                        {{ object.status }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Автор рассылки:</p>
                                    </td>
                                    <td>
                                        {{ object.user_owner }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Сообщение:</p>
                                    </td>
                                    <td>
                                        <details>
                                            <summary>{{ object.message }}</summary>
                                            <p>Текст сообщения:</p>{{ object.message.text }}
                                        </details>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Список клиентов, которые получат сообщение:</p>
                                    </td>
                                    <td>
                                        {% for client in object.clients.all %}
                                        <details>
                                            <summary>{{ client }}</summary>
                                            <table class="table">
                                                <tr>
                                                    <td>
                                                        Email:
                                                    </td>
                                                    <td>
                                                        {{ client.email }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Фамилия:
                                                    </td>
                                                    <td>
                                                        {{ client.surname }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Имя:
                                                    </td>
                                                    <td>
                                                        {{ client.name }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Отчество:
                                                    </td>
                                                    <td>
                                                        {{ client.patronymic }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Комментарий:
                                                    </td>
                                                    <td>
                                                        {{ client.comments }}
                                                    </td>
                                                </tr>
                                            </table>
                                        </details>
                                        {% endfor %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Включение/отключение рассылки:</p>
                                    </td>
                                    <td style="text-align: right">
                                            <input type="checkbox" name="{{ object.id }}" {% if object.is_active %}checked{% endif %}>&nbsp&nbsp&nbsp
                                            <button type="submit" class="btn btn-outline-secondary">Сохранить</button>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
                </center>

            {% endfor %}

            </table>
            </form>
        </div>
        <div class="card-footer">
            <center><a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a></center>
        </div>
    </div>
</div>

{% endblock %}

messaging/templates/messaging/user_mailing.html
{% extends 'messaging/base.html' %}

{% block content %}

<br>
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <div class="about-info">
                <table width=100% style="margin-bottom: 20px;">
                    <tr>
                        <td><h3 style="color: orange;">{{ title }}</h3></td>
                        <td style="text-align: right;"><a href="{% url 'messaging:create_mailing' %}" class="btn btn-outline-secondary">Добавить, новую рассылку</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <tr>
                    <td>
                        <p>Название</p>
                    </td>
                    <td>
                        <p>Начало</p>
                    </td>
                    <td>
                        <p>Завершение</p>
                    </td>
                    <td>
                        <p>Периодичность</p>
                    </td>
                    <td>
                        <p>Статус</p>
                    </td>
                    <td>
                        <p>Признак запуска</p>
                    </td>
                    <td>
                        <p>Сообщение</p>
                    </td>
                    <td>
                        <p>Список клиентов</p>
                    </td>
                    <td></td>
                    <td></td>
                </tr>

            {% for object in object_list %}


                <tr>
                    <td>
                        <a href="{% url 'messaging:user_view_mailing' object.id %}">{{ object.name }}</a>
                    </td>
                    <td>
                        {{ object.dtime_begin }}
                    </td>
                    <td>
                        {{ object.dtime_end }}
                    </td>
                    <td>
                        {{ object.frequency }}
                    </td>
                    <td>
                        {{ object.status }}
                    </td>
                    <td>
                        {{ object.is_active }}
                    </td>
                    <td>
                        {{ object.message }}
                    </td>
                    <td>
                        {% for client in object.clients.all %}
                        <a href="{% url 'messaging:view_client' client.id %}">{{ client }}</a><br/>
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'messaging:update_mailing' object.id %}" class="btn btn-outline-secondary">Изменить</a>
                    </td>
                    <td>
                        <a href="{% url 'messaging:delete_mailing' object.id %}" class="btn btn-outline-danger">Удалить</a>
                    </td>
                </tr>


            {% endfor %}

            </table>

        </div>
        <div class="card-footer">
            <center><a href="{% url 'messaging:home' %}" class="btn btn-outline-secondary">На главную</a></center>
        </div>
    </div>
</div>

{% endblock %}